version: 2.1

jobs:
  wizcli_scan:
    working_directory: ~/app
    docker:
      - image: cimg/node:17.2.0
    parameters:
      image:
        type: string
        default: "nginx:latest"
      policy:
        type: string
        default: "Default vulnerabilities policy"
    steps:
      - setup_remote_docker
      - checkout

      - run:
          name: Export AWS credentials
          command: |
            export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}

      - run:
          name: Install Terraform
          command: |
            curl -fsSL https://releases.hashicorp.com/terraform/1.8.5/terraform_1.8.5_linux_amd64.zip -o terraform.zip
            unzip terraform.zip
            sudo mv terraform /usr/local/bin/
            terraform -version

      - run:
          name: Download wizcli
          command: |
            sudo mkdir -p /wizcli
            sudo curl -o wizcli https://downloads.wiz.io/wizcli/latest/wizcli-linux-amd64
            sudo chmod +x ./wizcli

      - run:
          name: Authenticate to Wiz
          command: ./wizcli auth --id ${WIZCLI_ID} --secret ${WIZCLI_SECRET}

      - run:
          name: Scan public Docker image
          command: |
            docker pull << parameters.image >>
            ./wizcli docker scan --image << parameters.image >> --policy "<< parameters.policy >>"

      - run:
          name: Build and scan Dockerfile in repo
          command: |
            if [ -f Dockerfile ]; then
              docker build -t local-vulnerable-app .
              ./wizcli docker scan --image local-vulnerable-app --policy "<< parameters.policy >>"
            else
              echo "No Dockerfile found to scan"
            fi

      - run:
          name: Scan Terraform plan (IaC)
          command: |
            if [ -f main.tf ]; then
              terraform init
              terraform plan -out plan.tfplan
              terraform show -json plan.tfplan > plan.tfplan.json
              ./wizcli iac scan --path plan.tfplan.json
            else
              echo "No Terraform files found"
            fi

      - run:
          name: Scan Kubernetes manifests
          command: |
            YAML_FILES=$(find . -name "*.yaml" -o -name "*.yml" | wc -l)
            if [ "$YAML_FILES" -gt 0 ]; then
              ./wizcli iac scan --path .
            else
              echo "No Kubernetes YAML files found"
            fi

      - run:
          name: Generate & scan SBOM
          command: |
            if [ -f package.json ]; then
              ./wizcli sbom generate --source . --output sbom.spdx.json
              ./wizcli sbom scan --sbom sbom.spdx.json
            else
              echo "No package.json found for SBOM"
            fi

      - run:
          name: Upload SARIF (if present)
          command: |
            if [ -f results.sarif ]; then
              ./wizcli sarif upload --sarif-file results.sarif
            else
              echo "No SARIF file found"
            fi

workflows:
  version: 2
  build_workflow:
    jobs:
      - wizcli_scan
