version: 2.1

jobs:
  wizcli_scan:
    working_directory: ~/app
    docker:
      - image: cimg/node:17.2.0
    parameters:
      image:
        type: string
        default: "nginx:latest"
      policy:
        type: string
        default: "Default vulnerabilities policy"
    steps:
      - setup_remote_docker
      - checkout

      - run:
          name: Install Terraform
          command: |
            sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
            curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
            echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com focal main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
            sudo apt-get update && sudo apt-get install terraform -y
            terraform -version

      - run:
          name: Download wizcli
          command: |
            sudo mkdir -p /wizcli
            sudo curl -o wizcli https://downloads.wiz.io/wizcli/latest/wizcli-linux-amd64
            sudo chmod +x ./wizcli

      - run:
          name: Authenticate to Wiz
          command: ./wizcli auth --id ${WIZCLI_ID} --secret ${WIZCLI_SECRET}

      - run:
          name: Scan Docker image
          command: |
            docker pull << parameters.image >>
            ./wizcli docker scan --image << parameters.image >> --policy "<< parameters.policy >>"

      - run:
          name: Scan Terraform files
          command: |
            if [ -f main.tf ]; then
              terraform init
              terraform plan -out plan.tfplan
              terraform show -json plan.tfplan > plan.tfplan.json
              ./wizcli iac scan --path plan.tfplan.json
            else
              echo "No Terraform files found to scan"
            fi

workflows:
  version: 2
  build_workflow:
    jobs:
      - wizcli_scan
